<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{{ $voucher['voucher_number'] }}</title>
    <style>
        * { box-sizing: border-box; }
        body { font-family: DejaVu Sans, sans-serif; font-size: 11px; color: #1f2937; margin: 0; padding: 18px; }
        .header { border-bottom: 2px solid #1f2937; padding-bottom: 10px; margin-bottom: 14px; }
        .company { font-size: 14px; font-weight: bold; }
        .company-meta { color: #6b7280; font-size: 10px; margin-top: 2px; }
        .voucher-no { float: right; text-align: right; }
        .voucher-no .label { color: #6b7280; font-size: 9px; text-transform: uppercase; letter-spacing: 0.5px; }
        .voucher-no .num { font-size: 12px; font-weight: bold; }
        .title { text-align: center; font-size: 16px; font-weight: bold; letter-spacing: 1px; margin: 8px 0 14px; text-transform: uppercase; }
        .date-row { margin-bottom: 12px; }
        .date-row .label { color: #6b7280; font-size: 10px; }
        .date-row .value { font-weight: bold; }
        .amount-box {
            border: 2px solid #1f2937; padding: 12px; text-align: center;
            margin: 12px 0; background: #f9fafb;
        }
        .amount-box .label { color: #6b7280; font-size: 10px; text-transform: uppercase; letter-spacing: 0.5px; }
        .amount-box .value { font-size: 22px; font-weight: bold; margin-top: 4px; }
        .field { margin: 8px 0; padding-bottom: 6px; border-bottom: 1px dotted #d1d5db; }
        .field .label { color: #6b7280; font-size: 9px; text-transform: uppercase; letter-spacing: 0.5px; }
        .field .value { font-size: 12px; min-height: 16px; margin-top: 2px; }
        .signatures { margin-top: 24px; width: 100%; }
        .signatures td { width: 50%; vertical-align: top; padding: 0 12px; }
        .sig-line { border-bottom: 1px solid #1f2937; height: 30px; margin-bottom: 4px; }
        .sig-label { color: #6b7280; font-size: 9px; text-transform: uppercase; letter-spacing: 0.5px; text-align: center; }
        .sig-name { text-align: center; font-weight: bold; font-size: 11px; margin-top: 2px; }
        .footer { margin-top: 18px; text-align: center; color: #9ca3af; font-size: 9px; font-style: italic; }
    </style>
</head>
<body>
    <div class="header">
        <div class="voucher-no">
            <div class="label">Voucher No.</div>
            <div class="num">{{ $voucher['voucher_number'] }}</div>
        </div>
        <div class="company">{{ $tenant->name ?? '—' }}</div>
        @if(!empty($tenant->address) || !empty($tenant->phone))
            <div class="company-meta">
                {{ $tenant->address ?? '' }}
                @if(!empty($tenant->phone)) · {{ $tenant->phone }} @endif
            </div>
        @endif
    </div>

    <div class="title">{{ $voucher['title'] }}</div>

    <div class="date-row">
        <span class="label">Date:</span>
        <span class="value">{{ optional($voucher['date'])->format('d M Y') }}</span>
    </div>

    <div class="amount-box">
        <div class="label">Amount</div>
        <div class="value">{{ $tenant->currency ?? '' }} {{ number_format($voucher['amount'], 2) }}</div>
    </div>

    <div class="field">
        <div class="label">Purpose / Particulars</div>
        <div class="value">{{ $voucher['purpose'] ?? '—' }}</div>
    </div>

    @if(!empty($voucher['category']) || !empty($voucher['sub_category']))
        <div class="field">
            <div class="label">Category</div>
            <div class="value">
                {{ $voucher['category'] ?? '' }}
                @if(!empty($voucher['sub_category'])) — {{ $voucher['sub_category'] }} @endif
            </div>
        </div>
    @endif

    @if(!empty($voucher['reference']))
        <div class="field">
            <div class="label">Reference</div>
            <div class="value">{{ $voucher['reference'] }}</div>
        </div>
    @endif

    @if(!empty($voucher['notes']) && $voucher['notes'] !== $voucher['purpose'])
        <div class="field">
            <div class="label">Notes</div>
            <div class="value">{{ $voucher['notes'] }}</div>
        </div>
    @endif

    <table class="signatures" cellpadding="0" cellspacing="0">
        <tr>
            <td>
                <div class="sig-line"></div>
                <div class="sig-label">Given By (Signature & Date)</div>
                <div class="sig-name">{{ $voucher['given_by_name'] ?? '' }}</div>
            </td>
            <td>
                <div class="sig-line"></div>
                <div class="sig-label">Received By (Signature & Date)</div>
                <div class="sig-name">{{ $voucher['received_by_name'] ?? '' }}</div>
            </td>
        </tr>
    </table>

    <div class="footer">Generated by MoBilling — Petty Cash Voucher</div>
</body>
</html>
