#!/usr/bin/env bash
# Activate a white-label custom domain for a MoBilling tenant.
#
# Usage:  sudo ./enable-custom-domain.sh clients.acmehost.co.tz
#
# Prerequisites:
#   1. The tenant saved the domain under Settings -> Company -> Custom Portal Domain
#   2. The domain's DNS A record points at this server
#
# What it does: writes an nginx vhost (same app, new hostname), tests config,
# reloads nginx, then obtains a Let's Encrypt certificate via certbot --nginx.
set -euo pipefail

DOMAIN="${1:?usage: enable-custom-domain.sh <domain>}"
DOMAIN=$(echo "$DOMAIN" | tr '[:upper:]' '[:lower:]')
CONF="/etc/nginx/sites-available/${DOMAIN}"

if [[ -e "/etc/nginx/sites-enabled/${DOMAIN}" ]]; then
  echo "vhost already exists: ${DOMAIN}"; exit 1
fi

# sanity: DNS should resolve to this machine
echo "→ DNS check: ${DOMAIN} resolves to: $(dig +short "$DOMAIN" | tr '\n' ' ')"

cat > "$CONF" <<EOF
# White-label MoBilling portal domain (generated by enable-custom-domain.sh)
server {
    listen 80;
    listen [::]:80;
    server_name ${DOMAIN};

    root /var/www/html/MoBilling/unganisha-api/public;
    index index.php index.html;

    client_max_body_size 20M;

    location /api {
        try_files \$uri \$uri/ /index.php?\$query_string;
    }
    location /sanctum {
        try_files \$uri \$uri/ /index.php?\$query_string;
    }
    location /pesapal {
        try_files \$uri \$uri/ /index.php?\$query_string;
    }
    location /storage {
        alias /var/www/html/MoBilling/unganisha-api/storage/app/public;
        try_files \$uri \$uri/ =404;
    }
    location ~ \.php\$ {
        fastcgi_pass unix:/run/php/php8.2-fpm.sock;
        fastcgi_param SCRIPT_FILENAME \$realpath_root\$fastcgi_script_name;
        include fastcgi_params;
        fastcgi_hide_header X-Powered-By;
    }
    location /assets/ {
        root /var/www/html/MoBilling/mobilling-ui/dist;
        add_header Cache-Control "public, max-age=31536000, immutable";
        try_files \$uri =404;
    }
    location / {
        root /var/www/html/MoBilling/mobilling-ui/dist;
        add_header Cache-Control "no-cache";
        try_files \$uri \$uri/ /index.html;
    }
    location ~ /\.(?!well-known) {
        deny all;
    }
}
EOF

ln -s "$CONF" "/etc/nginx/sites-enabled/${DOMAIN}"
nginx -t
systemctl reload nginx
echo "→ HTTP vhost live for ${DOMAIN}"

# HTTPS via Let's Encrypt (adds the 443 block + redirect automatically)
certbot --nginx -d "$DOMAIN" --non-interactive --agree-tos --redirect \
  -m info@moinfo.co.tz || {
    echo "!! certbot failed — the domain works on HTTP; fix DNS and re-run:";
    echo "   certbot --nginx -d ${DOMAIN} --redirect";
  }

echo "✓ ${DOMAIN} is live. The portal will show the tenant's branding automatically."
